name: Userprofile Master

env:
  registry:  openhackg8i5trw0acr.azurecr.io
  repository:  devopsoh/api-userprofile
  webapp_name: openhackg8i5trw0userprofile
  resource_group: openhackg8i5trw0rg
  staging_url: https://openhackg8i5trw0userprofile-staging.azurewebsites.net/api/healthcheck/user
  production_url: https://openhackg8i5trw0userprofile.azurewebsites.net/api/healthcheck/user

defaults:
  run:
    shell: bash
    working-directory: apis/userprofile

on:
  issues:
    types: [closed]

jobs:
  deploy-prod:
    if: contains(github.event.issue.labels.*.name, 'manual-approval')
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: ${{ env.staging_url }}

    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp deployment slot swap --name ${{ env.webapp_name }} --resource-group ${{ env.resource_group }} --slot staging --target-slot production
